from __future__ import annotations

from typing import List, Protocol, runtime_checkable


@runtime_checkable
class Storage(Protocol):
    def put_file(self, local_path: str, path: str) -> None: ...
    def get_file(self, path: str, local_path: str) -> None: ...
    def put_bytes(self, data: bytes, path: str) -> None: ...
    def get_bytes(self, path: str) -> bytes: ...
    def list(self, prefix: str = "") -> List[str]: ...
    def list_all(self) -> List[str]: ...
